import type { Metadata } from "next";
import Header from "./components/header/page";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hela Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
      <Header></Header>
        {children}
        
      </body>
    </html>
  );
}
